{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py38-numpy"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.22.4"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py39-numpy"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.22.4"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py310-numpy"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.22.4"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2021-05-19T00:00:00Z",
        "vid": "b51cfaea-e919-11ec-9fba-080027240888"
    },
    "details": "Numpy reports:\n\n> At most call-sites for PyArray\\_DescrNew, there are no validations of its return,\n> but an invalid address may be returned.",
    "id": "FreeBSD-kernel-2022-0136",
    "modified": "2022-06-11T00:00:00Z",
    "published": "2022-06-11T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2021-41495"
        },
        {
            "type": "WEB",
            "url": "https://github.com/numpy/numpy/pull/20960"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "py-numpy -- Missing return-value validation of the function PyArray_DescrNew"
}
