{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "mutt"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "2.0.2"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2020-11-20T00:00:00Z",
        "vid": "dc132c91-2b71-11eb-8cfd-4437e6ad11c4"
    },
    "details": "Kevin J. McCarthy reports:\n\n> Mutt had incorrect error handling when initially connecting to an IMAP\n> server, which could result in an attempt to authenticate without enabling TLS.",
    "id": "FreeBSD-kernel-2020-0042",
    "modified": "2020-11-20T00:00:00Z",
    "published": "2020-11-20T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2020-28896"
        },
        {
            "type": "WEB",
            "url": "https://gitlab.com/muttmua/mutt/-/commit/04b06aaa3e0cc0022b9b01dbca2863756ebbf59a"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "mutt -- authentication credentials being sent over an unencrypted connection"
}
