{
    "schema_version": "1.7.0",
    "modified": "2024-04-28T00:00:00Z",
    "published": "2024-04-28T00:00:00Z",
    "id": "FBSD-2024-04-28",
    "summary": "py-social-auth-app-django -- Improper Handling of Case Sensitivity",
    "details": "<description xmlns=\"http://www.vuxml.org/apps/vuxml-1\">\n\t<body xmlns=\"http://www.w3.org/1999/xhtml\">\n\t<p>GitHub Advisory Database:</p>\n\t<blockquote cite=\"https://nvd.nist.gov/vuln/detail/CVE-2024-32879\">\n\t  <p>Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.</p>\n\t</blockquote>\n\t</body>\n    </description>",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2024-32879"
        },
        {
            "type": "WEB",
            "url": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3"
        }
    ],
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py39-social-auth-app-django"
            },
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "events": [
                        {
                            "fixed": "5.4.1"
                        },
                        {
                            "introduced": "0"
                        }
                    ]
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py310-social-auth-app-django"
            },
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "events": [
                        {
                            "fixed": "5.4.1"
                        },
                        {
                            "introduced": "0"
                        }
                    ]
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py311-social-auth-app-django"
            },
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "events": [
                        {
                            "fixed": "5.4.1"
                        },
                        {
                            "introduced": "0"
                        }
                    ]
                }
            ]
        }
    ],
    "database_specific": {
        "vid": "b3affee8-04d1-11ef-8928-901b0ef714d4",
        "discovery": "2024-04-24T00:00:00Z"
    }
}
