{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python39"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "3.9.22_1"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python310"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "3.10.17_1"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python311"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "3.11.12_1"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python312"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "3.12.10_1"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2025-05-15T00:00:00Z",
        "vid": "e587b52d-38ac-11f0-b7b6-dcfe074bd614"
    },
    "details": "cna@python.org reports:\n\n> There is an issue in CPython when using\n> `bytes.decode(\"unicode\\_escape\",\n> error=\"ignore|replace\")`. If you are not using the\n> \"unicode\\_escape\" encoding or an error handler your\n> usage is not affected. To work-around this issue you may stop\n> using the error= handler and instead wrap the bytes.decode()\n> call in a try-except catching the DecodeError.",
    "id": "FreeBSD-ports-2025-0118",
    "modified": "2025-05-24T00:00:00Z",
    "published": "2025-05-24T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2025-4516"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-4516"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "cpython -- Use-after-free in \"unicode_escape\" decoder with error handler"
}
